// scripts/dora-metrics.js
import fs from "fs";
import { execSync } from "node:child_process";
import path from "path";

const version = execSync("git describe --tags --always").toString().trim();
const commit = execSync("git rev-parse HEAD").toString().trim();
const branch = execSync("git rev-parse --abbrev-ref HEAD").toString().trim();
const releaseDate = new Date().toISOString();

console.log("📦 Generating DORA metrics...");
console.log({ version, commit, branch, releaseDate });

// ✅ Define config file path (now supports root or nested)
const configDir = "src/config";
const configPath = path.join(configDir, "getConfig.ts");

// 🧱 Ensure directory exists
if (!fs.existsSync(configDir)) {
  fs.mkdirSync(configDir, { recursive: true });
  console.log(`📁 Created missing directory: ${configDir}`);
}

// ✅ Create new config data
const newContent = `
// ⚙️ Auto-generated by post-deploy DORA script
// Do not edit manually — changes will be overwritten on next deploy

export const AppConfig = {
  version: "${version}",
  commit: "${commit}",
  branch: "${branch}",
  releaseDate: "${releaseDate}"
};

export default AppConfig;
`;

// 📝 Write file safely
fs.writeFileSync(configPath, newContent);
console.log(`✅ DORA metrics written to ${configPath}`);
