
// ⚙️ Auto-generated by post-deploy DORA script
// Do not edit manually — changes will be overwritten on next deploy

export const AppConfig = {
  version: "v1.0.0-5-g264885e",
  commit: "264885e4896d2363308e01105c46fad45892e17f",
  branch: "main",
  releaseDate: "2025-11-06T08:44:13.596Z"
};

export default AppConfig;
