
// ⚙️ Auto-generated by post-deploy DORA script
// Do not edit manually — changes will be overwritten on next deploy

export const AppConfig = {
  version: "v1.0.0",
  commit: "6dd78c5d7e3fd35a7d887381be8e7d5b06618cb1",
  branch: "main",
  releaseDate: "2025-11-05T13:20:44.780Z"
};

export default AppConfig;
